-- MySQL Script generated by MySQL Workbench
-- Tue Aug 20 23:22:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mybudget
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mybudget
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mybudget` DEFAULT CHARACTER SET utf8mb3 ;
USE `mybudget` ;

-- -----------------------------------------------------
-- Table `mybudget`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mybudget`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `currency` VARCHAR(8) NOT NULL,
  `balance` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mybudget`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mybudget`.`transaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `amount` DECIMAL(8,2) NOT NULL,
  `currency` VARCHAR(8) NOT NULL,
  `Account_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Transaction_Account`
    FOREIGN KEY (`Account_id`)
    REFERENCES `mybudget`.`account` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 64
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
